### ISSUE TITLE
Add FR245, FR245M, FR745 & FR945

### ISSUE THREAD

**Issue by rjdverbeek-tud** [klarh/garmin_google_tasks#2]
Dear Matthew,

I noticed that some common Garmin watches are not in the list. Could they be added?

FR245, FR245M, FR745 & FR945

Wkr, Rene

**Comment by klarh** [comment]
These devices have been added to the list as of 1c6bcd1ba373406fb9f9de359538c2b4660f7d57 and v0.3.5 has been pushed to the store. Sorry for the delay!

**Comment by rjdverbeek** [comment]
Tx
